# typed: false
# frozen_string_literal: true

# Homebrew formula for Numan (Nushell package manager).
#
# Tap install (HTTPS remote avoids SSH host-key update failures):
#   brew tap tonythethompson/numan https://github.com/tonythethompson/homebrew-numan
#   brew install numan
#
# Generated by scripts/render_homebrew_formula.py — do not hand-edit digests.
# The Publish to Homebrew workflow updates this file and the homebrew-numan tap
# after each v*.*.* GitHub Release.
#
# Snapshot note: this checked-in copy may lag the renderer. It currently omits
# the Linux ARM (on_linux/on_arm) stanza until a release publishes
# aarch64-unknown-linux-gnu digests; see packaging/homebrew/README.md.

class Numan < Formula
  desc "Cross-platform package manager for Nushell"
  homepage "https://github.com/tonythethompson/numan"
  version "0.1.5"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/tonythethompson/numan/releases/download/v#{version}/numan-#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "4d8fa065b5bc7fcce30af3ca7d5c3cd943701bee168d78fae6120a12689738b8"
    end
    on_intel do
      odie "Numan no longer ships Intel Mac (x86_64) binaries. Use Apple Silicon, or `cargo install numan-cli`."
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tonythethompson/numan/releases/download/v#{version}/numan-#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "0b113361c189a2062ef6e1fca36795d2347b925c1862b42c4ddeb54773e00ae3"
    end
  end

  def install
    # Homebrew stages into the archive's sole top-level directory, so the
    # binary is ./numan (not ./numan-*/numan).
    bin.install "numan"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/numan --version")
  end
end
